main: dev.jsinco.malts.Malts
name: Malts
version: '${version}'
api-version: 1.21
author: Jsinco
description: An open-source and free Vaults plugin that incorporates a warehouse for mass item storage.
website: github.com/BreweryTeam/Malts
load: POSTWORLD
commands:
  malts:
    description: Main command for Malts
  vaults:
    description: Alias for /malts vaults <index?>
    aliases: [pv, vault, vaults, chest]
  warehouse:
    description: Alias for /malts warehouse
    aliases: [es, wh]
permissions:
  malts.*:
    description: A permission node for Malts intended for admins.
    default: op
    children:
      malts.admin: true
  malts.admin:
    description: A permission node for Malts intended for admins.
    default: op
    children:
      malts.command.*: true
      malts.mod: true
      malts.bypass.*: true
  malts.mod:
    description: A permission node for Malts intended for staff members. Also allows a player to open a vault at the same time as another player.
    default: op
    children:
      malts.command.vaultadmin: true
      malts.command.warehouseadmin: true
      malts.bypass.openvault: true
  malts.default:
    description: A permission node for Malts intended for players.
    default: true
    children:
      malts.command.base: true
      malts.command.help: true
      malts.command.vaults: true
      malts.command.vaultother: true
      malts.command.warehouse: true
  malts.command.*:
    children:
      malts.command.base: true
      malts.command.help: true
      malts.command.import: true
      malts.command.max: true
      malts.command.reload: true
      malts.command.vaultadmin: true
      malts.command.vaultother: true
      malts.command.vaults: true
      malts.command.warehouseadmin: true
      malts.command.warehouse: true
  malts.bypass.*:
    children:
      malts.bypass.openvault: true
      malts.bypass.economy: true
  malts.bypass.openvault:
    description: Allows a player to bypass vault opening checks.
    default: op
  malts.bypass.economy:
    description: Allows a player to bypass economy checks.
    default: op