main: dev.jsinco.gringotts.Gringotts
name: Gringotts
version: 1.0.0
api-version: 1.21
commands:
  gringotts:
    description: Main command for Gringotts
  playervaults:
    description: Alias for /gringotts vaults <index?>
    aliases: [pv, vault]
  warehouse:
    description: Alias for /gringotts warehouse
    aliases: [es, wh]
permissions:
  gringotts.viewother:
    children:
      gringotts.command.vaultothers: true
      gringotts.command.warehouseadmin: true