name: "Publish to Modrinth, Hangar, Maven, and post to Discord"

on:
  release:
    branches: [master]
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to Hangar
        run: "./gradlew publishAllPublicationsToHangar"
        env:
          CHANGE_LOG: ${{ github.event.release.body }}
          HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
      - name: Publish to Modrinth
        run: "./gradlew modrinth"
        env:
          CHANGE_LOG: ${{ github.event.release.body }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - name: Post to BreweryTeam Discord
        run: "./gradlew publishToDiscord"
        env:
          CHANGE_LOG: ${{ github.event.release.body }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Publish API
        run: "./gradlew publish"
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_SECRET: ${{ secrets.REPO_SECRET }}
